Rename scale to channel
vizzuhq/vizzu-lib pull request #205
Opened 2023-06-12 15:01 UTC by schaumb

2023-06-12 18:45 UTC, simzer requested changes

2023-06-13 10:43 UTC, schaumb commented
I'll wait for the merge until https://github.com/vizzuhq/vizzu-lib/pull/202 accepted.

2023-06-13 10:50 UTC, simzer commented
I have merged #202

2023-06-13 13:27 UTC, simzer approved these changes

2023-06-13 13:27 UTC, merged