NumToStr fix with charconv
vizzuhq/vizzu-lib pull request #223
Opened 2023-06-20 18:36 UTC by schaumb

2023-06-20 18:46 UTC, schaumb commented
@veghdev Please update gcc to at least version 12 in test machine (newer is better). The emcc uses the gcc standard lib, and gcc10 is not C++20 compliant.

2023-06-21 10:16 UTC, simzer requested changes
This implementation increases the binary size with 107KB (27%). Most likely because it uses the locale.

2023-06-22 09:14 UTC, schaumb commented
And this will not work, because switched off rtti.
-->

https://stackoverflow.com/questions/49939459/c-locale-without-rtti

2023-06-22 09:42 UTC, simzer commented
Yep, but also, I think it would not prevent the compiler to link the needed infrastructure for locales.

2023-06-22 13:07 UTC, simzer submitted a review, later dismissed

2023-06-22 15:24 UTC, schaumb commented on CHANGELOG.md
> +- Fixed showing big doubles greater than UINT64_MAX.
"Fixed showing big numbers greater than 18446744073709551615." is OK?

2023-06-22 15:35 UTC, simzer commented on CHANGELOG.md
> +- Fixed showing big doubles greater than UINT64_MAX.
OK

2023-06-22 15:40 UTC, simzer submitted a review, later dismissed

2023-06-22 16:30 UTC, merged