Orientation selector
vizzuhq/vizzu-lib pull request #271
Opened 2023-07-10 17:13 UTC by schaumb

2023-07-11 19:54 UTC, simzer commented
reason for some test fail: up to this point, orientation selection run after all individual config parameter change. This caused a dependence of the final orientation on the order of the x, y channel setting. This was an unwanted behavior.

2023-07-17 10:40 UTC, schaumb commented
If I only sort X and Y, only 27 tc fails.

2023-09-11 12:12 UTC, simzer approved these changes

2023-09-11 12:12 UTC, simzer commented on src/chart/animator/planner.cpp
> +	if (*srcOpt->orientation.get() != *trgOpt->orientation.get()
Could be isHorizontal() as well.

2023-09-11 12:25 UTC, simzer requested changes
Please add a note to the changelog

2023-09-11 14:17 UTC, simzer approved these changes

2023-09-11 15:57 UTC, merged