fix json escape
vizzuhq/vizzu-lib pull request #465
Opened 2024-01-08 12:21 UTC by schaumb

2024-01-08 14:35 UTC, simzer submitted a review, later dismissed

2024-01-09 12:30 UTC, simzer reviewed
Shouldn't we escape the object keys as well?

2024-01-09 12:32 UTC, simzer requested changes
Changing back from approved because open question.

2024-01-09 12:40 UTC, schaumb commented
> Shouldn't we escape the object keys as well?

There is a [template argument](https://github.com/vizzuhq/vizzu-lib/blob/f4508fc41ac8acf455e4f1c76132db2593d4cc91/src/base/conv/auto_json.h#L292) for that. By default, it's not because the reflected member names are used as keys, which cannot contain escapable characters.

But there is a bug [here](https://github.com/vizzuhq/vizzu-lib/pull/463/files#diff-ceeaf2623a7d23f860fbf1d35cb31db4355c0652d82d69f5f0076821bd605620R298).

2024-01-09 17:26 UTC, simzer approved these changes

2024-01-09 18:07 UTC, merged